#!/usr/bin/env bash

# for java applications
wmname LG3D

# keybaord shortcut daemon
sxhkd &

# polybar
$HOME/.config/polybar/launch.sh

# Wallpaper - pywal
$HOME/.local/bin/wal -i $HOME/Pictures/Wallpapers/

# Gnome services
#exec --no-startup-id /usr/lib/gsd-xsettings
#exec_always --no-startup-id gnome-power-manager
#exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
#exec --no-startup-id gnome-flashback
#exec --no-startup-id /usr/bin/gnome-screensaver

# handle monitors
bspc monitor HDMI-0 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Firefox desktop='^2'
#bspc rule -a "Google Chrome" desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

